# Используем официальный Node.js образ
FROM node:18

# Создаём рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальной исходный код
COPY . .

# Собираем приложение NestJS (если используешь TypeScript)
RUN npm run build

# Указываем порт
EXPOSE 5000
